In [1]:
"Hello World!"

'Hello World!'

In [2]:
'Hello World!'

'Hello World!'

In [4]:
hello = "Hello!"
hello

'Hello!'

In [9]:
world = "World!"
1 + world

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [12]:
"Hello {} {} {}".format("David", "John", "Alice")

'Hello David John Alice'

In [13]:
"         Hellooooooo".strip()

'Hellooooooo'

In [14]:
hello

'Hello!'

In [15]:
type(hello)

str

In [16]:
hello = 3.1419

In [17]:
type(hello)

float

In [18]:
hello.strip()

AttributeError: 'float' object has no attribute 'strip'

In [20]:
my_tuple = ('Hello', 5)
my_tuple

('Hello', 5)

In [21]:
my_tuple[0]

'Hello'

In [22]:
my_tuple[1]

5

In [23]:
numbers = [1, 3, 14, 2.78, 1.61]
numbers

[1, 3, 14, 2.78, 1.61]

In [24]:
numbers[0]

1

In [25]:
hello_world = ["Hello", "World"]
hello_world

['Hello', 'World']

In [26]:
mixed_types_list = [1, 2, 3, "Four", "Five", "Six"]
mixed_types_list

[1, 2, 3, 'Four', 'Five', 'Six']

In [27]:
numbers[2]

14

In [28]:
mixed_types_list[6]

IndexError: list index out of range

In [29]:
mixed_types_list[-1]

'Six'

In [30]:
mixed_types_list[len(mixed_types_list)]

IndexError: list index out of range

In [31]:
len(mixed_types_list)

6

In [33]:
mixed_types_list[len(mixed_types_list)-2]

'Five'

In [34]:
mixed_types_list[-2]

'Five'

In [35]:
numbers

[1, 3, 14, 2.78, 1.61]

In [36]:
numbers[2:4]

[14, 2.78]

In [38]:
sorted(numbers)

[1, 1.61, 2.78, 3, 14]

In [40]:
mixed_types_list

[1, 2, 3, 'Six', 'Four', 'Five']

In [41]:
mixed_types_list.sort(reverse=True)

TypeError: '<' not supported between instances of 'int' and 'str'

In [43]:
numbers.sort(reverse=True)
numbers

[14, 3, 2.78, 1.61, 1]

In [45]:
sorted_numbers = sorted(numbers)
sorted_numbers

[1, 1.61, 2.78, 3, 14]

In [46]:
numbers

[14, 3, 2.78, 1.61, 1]

In [47]:
numbers.append(365)
numbers

[14, 3, 2.78, 1.61, 1, 365]

In [52]:
my_tuple.append(365)

AttributeError: 'tuple' object has no attribute 'append'

In [50]:
sorted((1, 3, 5, 1 ,5))

[1, 1, 3, 5, 5]

In [51]:
my_other_tuple = tuple(sorted((1, 3, 5, 1 ,5)))
my_other_tuple

(1, 1, 3, 5, 5)

In [53]:
breakfast = {
    "eggs": 1,
    "bacon": 2,
    "sausage": 10,
    "spam": 4
}
breakfast

{'bacon': 2, 'eggs': 1, 'sausage': 10, 'spam': 4}

In [54]:
breakfast['sausage']

10

In [56]:
breakfast['sausage'] = "No thanks, I don't like sausage."
breakfast

{'bacon': 2,
 'eggs': 1,
 'sausage': "No thanks, I don't like sausage.",
 'spam': 4}

In [57]:
breakfast['pancakes'] = "Yes please!"
breakfast

{'bacon': 2,
 'eggs': 1,
 'pancakes': 'Yes please!',
 'sausage': "No thanks, I don't like sausage.",
 'spam': 4}

In [58]:
breakfast.keys()

dict_keys(['eggs', 'bacon', 'sausage', 'spam', 'pancakes'])

In [59]:
breakfast.values()

dict_values([1, 2, "No thanks, I don't like sausage.", 4, 'Yes please!'])

In [60]:
import numpy as np
import pandas as pd

In [61]:
a = [1, 2, 3, 4, 5, 6]
b = [20, 30, 40 , 50, 60, 70]
a + b 

[1, 2, 3, 4, 5, 6, 20, 30, 40, 50, 60, 70]

In [62]:
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [63]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [64]:
A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([20, 30, 40, 50, 60, 70])
A

array([1, 2, 3, 4, 5, 6])

In [65]:
a

[1, 2, 3, 4, 5, 6]

In [68]:
C = A + B
C

array([21, 32, 43, 54, 65, 76])

In [69]:
A = np.array(a)
B = np.array(b)

In [70]:
A * B

array([ 20,  60, 120, 200, 300, 420])

In [71]:
A + B

array([21, 32, 43, 54, 65, 76])

In [72]:
A - B

array([-19, -28, -37, -46, -55, -64])

In [73]:
B - A

array([19, 28, 37, 46, 55, 64])

In [77]:
A + np.array([2, 3])

ValueError: operands could not be broadcast together with shapes (6,) (2,) 

In [79]:
array1 = np.array([14.1, 15.2, 16.3])
series1 = pd.Series(array1)

In [80]:
array1

array([14.1, 15.2, 16.3])

In [81]:
series1

0    14.1
1    15.2
2    16.3
dtype: float64

In [94]:
features = {
    'animals': ['python', 'lynx', 'giant panda', 'field mouse', 'octopus'],
    'limbs': [0, 4, 4, 4, 8],
    'herbivore': [False, False, True, True, False]
}
df = pd.DataFrame(features, index=features['animals'])
df

animals  herbivore  limbs
python            python      False      0
lynx                lynx      False      4
giant panda  giant panda       True      4
field mouse  field mouse       True      4
octopus          octopus      False      8

In [95]:
df.head(3)

animals  herbivore  limbs
python            python      False      0
lynx                lynx      False      4
giant panda  giant panda       True      4

In [96]:
df.sample(2)

animals  herbivore  limbs
lynx        lynx      False      4
octopus  octopus      False      8

In [97]:
df['limbs']

python         0
lynx           4
giant panda    4
field mouse    4
octopus        8
Name: limbs, dtype: int64

In [98]:
type(df['limbs'])

pandas.core.series.Series

In [99]:
df.loc['python']

animals      python
herbivore     False
limbs             0
Name: python, dtype: object

In [100]:
type(df.loc['python'])

pandas.core.series.Series

In [101]:
df.describe()

limbs
count  5.000000
mean   4.000000
std    2.828427
min    0.000000
25%    4.000000
50%    4.000000
75%    4.000000
max    8.000000

In [102]:
df['herbivore'].describe()

count         5
unique        2
top       False
freq          3
Name: herbivore, dtype: object